import { DataType } from './Items.type';
const tableData: DataType[] = [
    {
        key: '1428571',
        name: 'iphone 15',
        code: 'I-003800',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1000,
        stock: 10,
        status: true,
    },
    {
        key: '2857143',
        name: 'iphone 15',
        code: 'I-003800',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1000,
        stock: 10,
        status: true,
    },
    {
        key: '4285714',
        name: 'iphone 16',
        code: 'I-003801',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1100,
        stock: 5,
        status: false,
    },
    {
        key: '5714286',
        name: 'iphone 17',
        code: 'I-003802',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1200,
        stock: 8,
        status: true,
    },
    {
        key: '7142857',
        name: 'iphone 18',
        code: 'I-003803',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1300,
        stock: 12,
        status: true,
    },
    {
        key: '8571429',
        name: 'iphone 19',
        code: 'I-003804',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1400,
        stock: 1,
        status: false,
    },
    {
        key: '1000000',
        name: 'iphone 20',
        code: 'I-003805',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1500,
        stock: 7,
        status: true,
    },
    {
        key: '1428572',
        name: 'iphone 21',
        code: 'I-003806',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1600,
        stock: 3,
        status: true,
    },
    {
        key: '2857144',
        name: 'iphone 22',
        code: 'I-003807',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1700,
        stock: 11,
        status: false,
    },
    {
        key: '4285715',
        name: 'iphone 23',
        code: 'I-003808',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1800,
        stock: 9,
        status: true,
    },
    {
        key: '5714288',
        name: 'iphone 24',
        code: 'I-003809',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1900,
        stock: 15,
        status: false,
    },
];

export { tableData };
