import { DataType } from './Items.type';

const tableData: DataType[] = [
    {
        key: '123',
        name: 'iphone 15',
        code: 'I-003800',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1000,
        stock: 10,
        status: true,
    },
    {
        key: '123',
        name: 'iphone 15',
        code: 'I-003800',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1000,
        stock: 10,
        status: true,
    },
    {
        key: '124',
        name: 'iphone 16',
        code: 'I-003801',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1100,
        stock: 5,
        status: false,
    },
    {
        key: '125',
        name: 'iphone 17',
        code: 'I-003802',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1200,
        stock: 8,
        status: true,
    },
    {
        key: '126',
        name: 'iphone 18',
        code: 'I-003803',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1300,
        stock: 12,
        status: true,
    },
    {
        key: '127',
        name: 'iphone 19',
        code: 'I-003804',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1400,
        stock: 1,
        status: false,
    },
    {
        key: '128',
        name: 'iphone 20',
        code: 'I-003805',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1500,
        stock: 7,
        status: true,
    },
    {
        key: '129',
        name: 'iphone 21',
        code: 'I-003806',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1600,
        stock: 3,
        status: true,
    },
    {
        key: '130',
        name: 'iphone 22',
        code: 'I-003807',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1700,
        stock: 11,
        status: false,
    },
    {
        key: '131',
        name: 'iphone 23',
        code: 'I-003808',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1800,
        stock: 9,
        status: true,
    },
    {
        key: '132',
        name: 'iphone 24',
        code: 'I-003809',
        categories: 'Mobile',
        type: 'Product',
        brand: 'Apple',
        color: '#000',
        size: 'N/A',
        salePrice: 1900,
        stock: 15,
        status: false,
    },
];

export { tableData };
