// unitOptions.ts
export const unitOptions = [
    {
        label: 'Paper',
        options: [
            { label: 'Sheet', value: 'Sheet' },
            { label: 'Quire', value: 'Quire' },
            { label: 'Ream', value: 'Ream' },
            { label: 'Bundle', value: 'Bundle' },
        ],
    },
    {
        label: 'Quantity',
        options: [
            { label: 'Piece', value: 'Piece' },
            { label: 'Pair', value: 'Pair' },
            { label: 'Dozen', value: 'Dozen' },
            { label: 'Gross', value: 'Gross' },
        ],
    },
    {
        label: 'Time',
        options: [
            { label: 'Second', value: 'Second' },
            { label: 'Millisecond', value: 'Millisecond' },
            { label: 'Microsecond', value: 'Microsecond' },
            { label: 'Nanosecond', value: 'Nanosecond' },
            { label: 'Picosecond', value: 'Picosecond' },
            { label: 'Minute', value: 'Minute' },
            { label: 'Hour', value: 'Hour' },
            { label: 'Day', value: 'Day' },
            { label: 'Week', value: 'Week' },
            { label: 'Month', value: 'Month' },
            { label: 'Year', value: 'Year' },
        ],
    },
    {
        label: 'Weight',
        options: [
            { label: 'Kilogram', value: 'Kilogram' },
            { label: 'Gram', value: 'Gram' },
            { label: 'Milligram', value: 'Milligram' },
            { label: 'Metric Ton', value: 'Metric Ton' },
            { label: 'Long Ton', value: 'Long Ton' },
            { label: 'Short Ton', value: 'Short Ton' },
            { label: 'Pound', value: 'Pound' },
            { label: 'Ounce', value: 'Ounce' },
            { label: 'Carrat', value: 'Carrat' },
            { label: 'Atomic Mass Unit', value: 'Atomic Mass Unit' },
        ],
    },
    {
        label: 'Volume',
        options: [
            { label: 'Cubic Meter', value: 'Cubic Meter' },
            { label: 'Cubic Kilometer', value: 'Cubic Kilometer' },
            { label: 'Cubic Centimeter', value: 'Cubic Centimeter' },
            { label: 'Cubic Millimeter', value: 'Cubic Millimeter' },
            { label: 'Liter', value: 'Liter' },
            { label: 'Millilitre', value: 'Millilitre' },
            { label: 'US Gallon', value: 'US Gallon' },
            { label: 'US Quart', value: 'US Quart' },
            { label: 'US Pint', value: 'US Pint' },
            { label: 'US-Cup', value: 'US-Cup' },
            { label: 'US Fluid Ounce', value: 'US Fluid Ounce' },
            { label: 'US Table Spoon', value: 'US Table Spoon' },
            { label: 'US Tea Spoon', value: 'US Tea Spoon' },
            { label: 'Imperial Gallon', value: 'Imperial Gallon' },
            { label: 'Imperial Quart', value: 'Imperial Quart' },
            { label: 'Imperial Pint', value: 'Imperial Pint' },
            { label: 'Imperial Fluid Ounce', value: 'Imperial Fluid Ounce' },
            { label: 'Imperial Table Spoon', value: 'Imperial Table Spoon' },
            { label: 'Imperial Tea Spoon', value: 'Imperial Tea Spoon' },
            { label: 'Cubic Mile', value: 'Cubic Mile' },
            { label: 'Cubic Yard', value: 'Cubic Yard' },
            { label: 'Cubic Foot', value: 'Cubic Foot' },
            { label: 'Cubic Inch', value: 'Cubic Inch' },
        ],
    },
    {
        label: 'Area',
        options: [
            { label: 'Square-Meters', value: 'Square-Meters' },
            { label: 'Square-Kilometers', value: 'Square-Kilometers' },
            { label: 'Square-Centimeters', value: 'Square-Centimeters' },
            { label: 'Square-Millimeters', value: 'Square-Millimeters' },
            { label: 'Square-Micrometers', value: 'Square-Micrometers' },
            { label: 'Hectares', value: 'Hectares' },
            { label: 'Square-Mile', value: 'Square-Mile' },
            { label: 'Square-Yards', value: 'Square-Yards' },
            { label: 'Square-Feet', value: 'Square-Feet' },
            { label: 'Square-Inches', value: 'Square-Inches' },
            { label: 'Acres', value: 'Acres' },
        ],
    },
    {
        label: 'Temperature',
        options: [
            { label: 'Celsius', value: 'Celsius' },
            { label: 'Kelvin', value: 'Kelvin' },
            { label: 'Fahrenheit', value: 'Fahrenheit' },
        ],
    },
    {
        label: 'Length',
        options: [
            { label: 'Meters', value: 'Meters' },
            { label: 'Kilometers', value: 'Kilometers' },
            { label: 'Centimeters', value: 'Centimeters' },
            { label: 'Millimeters', value: 'Millimeters' },
            { label: 'Micrometers', value: 'Micrometers' },
            { label: 'Nanometers', value: 'Nanometers' },
            { label: 'Miles', value: 'Miles' },
            { label: 'Yards', value: 'Yards' },
            { label: 'Foot', value: 'Foot' },
            { label: 'Inches', value: 'Inches' },
        ],
    },
];
